### ISSUE TITLE
[BUG] Crash server spam right clicking holding book and quill

### ISSUE THREAD

**Issue by Bruhhhh10** [oraxen/oraxen#1131]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

you can crash any server that's using Oraxen, I tested this without oraxen and it doesn't cause lag at all.

### Steps to reproduce

Grab a book and quill, fill all pages, sign it
Right click it against an Oraxen block, the server will lag a ton, or you could spam it
When you right click the written book against a minecraft block it wont cause any lag, if you right click against an Oraxen block or just air it will cause lag and will crash the server if you spam it

### Plugin Version

1.164.0

### ProtocolLib Version

5.1.1-SNAPSHOT-673

### Server Software & Version

git-Paper-298 (MC: 1.20.2)

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
think this is fixed in 1.165.0
i can atleast not replicate it with a page full with 100 pages

**Comment by Bruhhhh10** [comment]
> think this is fixed in 1.165.0 i can atleast not replicate it with a page full with 100 pages

Just compiled 1.165.0 and it seems it's still not fixed, same error same amount of lag
