### ISSUE TITLE
[BUG] Breaking noteblock doesn't make block.wood.hit sound

### ISSUE THREAD

**Issue by Bruhhhh10** [oraxen/oraxen#1177]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Breaking noteblock doesn't make block.wood.hit sound

I do have replace sounds enabled in sounds.yml for block.wood.hit, if I turn it off it works fine

### Steps to reproduce

https://github.com/oraxen/oraxen/assets/134551265/45971582-8f78-4f2d-af0e-1e1bf7851da5

### Plugin Version

1.166.0

### ProtocolLib Version

 5.1.1-SNAPSHOT-673

### Server Software & Version

 git-Paper-370 (MC: 1.20.4)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
fixed in #1166

**Comment by Bruhhhh10** [comment]
> fixed in #1166

@Boy0000 Just tried in both versions 1.167.0 and 1.168.0, it isn't fixed
