### ISSUE TITLE
[BUG] Conflict with Advanced Crates or ClickEvent on Barrier block for Furnitures

### ISSUE THREAD

**Issue by RenardFarceur** [oraxen/oraxen#737]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Hi there : 
I want to post an issue that is quit problematic : after the version 1.150.4 of Oraxen my crates don't work anymore with Advanced Crates : The crates aren't previewable from a left click. The issue is on all "furnitures". I have search for like 4 hours which plugin was doing this but to see that's an Oraxen problem : What changes from here ? Can you fix this soon ? It's like 1 month + that my crates are broken and replaced by a diamond block T_T.
I've finding with trying everything in local, try to remove as much plugin as I can to see if there is a conflict. But downgrade my Oraxen version was the only solution
Sorry for not searching before !
Thank you Boy & others for your awesome work !
https://mclo.gs/qjq315d oraxen dump_log
https://hastebin.com/share/xojezulime.yaml my furniture config
https://hastebin.com/share/abawemikoz.yaml my setting.yml

### Steps to reproduce

Install any version between 1.150.4 & latest
Use Advanced crates on any furniture (personnalized one or include in basic pack). /ac set on a furniture, can't click left on a crate to preview

### Plugin Version

1.152.5 but no really matter ^^'

### ProtocolLib Version

: ProtocolLib version 5.0.0-SNAPSHOT-b610

### Server Software & Version

Paper-425 (MC: 1.19.3)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by TheDeadSnake** [comment]
Bug #510 that was fixed in #514 seems to have been commented out in 21c1d40a6c1ce98bbb78ee78a1433f6cdecd2777.

```
//scheduler.runTask(OraxenPlugin.get(), () -> Bukkit.getPluginManager().callEvent(playerInteractEvent));
if (playerInteractEvent.useInteractedBlock().equals(Event.Result.DENY)) return;
```

(Most likely because the return value was being ignored. As it's run using the scheduler to prevent it from being called on the network thread, but in return can not be Cancelled).

**Comment by RenardFarceur** [comment]
Still not fixed, I can't put any crate on custom furniture made with Oraxen. Same issue

**Comment by Boy0000** [comment]
@RenardFarceur because it hasnt been added yet
1.155.2 PR has it fixed in its changelog
