### ISSUE TITLE
[BUG] getMechanic returns null for FastAsyncWorldEdit //set

### ISSUE THREAD

**Issue by noiverre** [oraxen/oraxen#967]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When using Oraxen NoteBlock mechanics to //set blocks in FAWE, this error happen
https://paste.gg/p/anonymous/185c0cd79d314622904854e7675074fb
![image](https://github.com/oraxen/oraxen/assets/77881970/a5fd053d-d967-4cac-9f88-84569afd7214)

Error may happen in regular WorldEdit, however, I haven't tested it yet

### Steps to reproduce

```
all_sided_blast_enchanting_table:
  displayname: <white>All Sided Enchanting Table
  material: PAPER
  Pack:
    generate_model: true
    custom_model_data: 1003005
    parent_model: block/cube_all
    textures:
    - block/enchanting_table_top.png
  Mechanics:
    noteblock:
      model: all_sided_blast_enchanting_table
      custom_variation: 305
      hardness: 20
      drop:
        minimal_type: STONE
        best_tools:
        - PICKAXE
        silktouch: false
        loots:
        - oraxen_item: all_sided_blast_enchanting_table
          probability: 1.0
```
```
  worldedit: # Please note these are both experimental still and should be used with caution
    noteblock_mechanic: true
    stringblock_mechanic: false # Works, but is buggy with some stringblocks, specifically with Tall-property
```

Set pos1 and pos2
//set oraxen:all_sided_blast_enchanting_table

### Plugin Version

![image](https://github.com/oraxen/oraxen/assets/77881970/00520ccb-913b-4a89-808c-db1b455c595e)

### ProtocolLib Version

![image](https://github.com/oraxen/oraxen/assets/77881970/6ac9000d-61d9-44d1-b2ec-573519e20779)

### Server Software & Version

![image](https://github.com/oraxen/oraxen/assets/77881970/1239d474-e13d-469d-b9ba-aeae3d906166)
https://github.com/AtlasMediaGroup/Scissors

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
Unable to replicate this. Have you disabled NoteBlock-mechanic in mechanics.yml?

https://github.com/oraxen/oraxen/assets/62521371/8d4da2ee-a1fd-4ab3-850b-449111fcd960

**Comment by noiverre** [comment]
It's true in mechanics.yml
```
noteblock:
  tool_types:
  - WOODEN
  - STONE
  - IRON
  - GOLDEN
  - DIAMOND
  - NETHERITE
  - null
  farmblock_check_delay: 1000
  enabled: true
```

FAWE:
```
extent:
  # Don't bug console when these plugins slow down WorldEdit operations
  #  - You'll see a message in console or ingame if you need to change this option
  allowed-plugins: 
  - "com.example.ExamplePlugin"
  - "io.th0rgal.oraxen.compatibilities.provided.worldedit.WorldEditHandlers$1"
  # Should debug messages be sent when third party extents are used?
  debug: true
```

**Comment by noiverre** [comment]
Perhaps it's because I don't use FAWE from https://ci.athion.net/job/FastAsyncWorldEdit/

I used FAWE from https://ci.athion.net/job/FAWE-PS-v7/ to support PlotSquared V7

**Comment by Boy0000** [comment]
works without issues for me
I pushed some small changes to 1.158.1 PR, if you compile that, if u know how, see if that works

**Comment by noiverre** [comment]
I reproduced the steps with 1.158.1 branch build, still persist
Switched FAWE from FAWE-PS-v7 to https://ci.athion.net/job/FastAsyncWorldEdit/, still persist
![image](https://github.com/oraxen/oraxen/assets/77881970/3fefadc6-a41d-4755-aed5-574477653769)

Should I report this to FAWE developers?

**Comment by Boy0000** [comment]
no i doubt this is a FAWE issue seeing as im entirely unable to replicate this

**Comment by noiverre** [comment]
I can provide more informations, but not sure which

**Comment by Boy0000** [comment]
yeah no clue
When i restart my server fully, am on 1.158.1 branch, and use any FAWE and even your blocks config
Works without issues

**Comment by Boy0000** [comment]
idk what your fork is but please replicate bugs on Paper and not some obscure fork

**Comment by noiverre** [comment]
Reproduced with latest Paper, master branch of Oraxen, and FAWE-PS-v7

https://paste.gg/p/anonymous/b8dfbef4362044088bfaabbd20d20d1a

```
[05:42:21] [Server thread/INFO]: Oraxen version 1.158.0
[05:42:21] [Server thread/INFO]: Authors: th0rgal and boy0000
[05:42:23] [Server thread/INFO]: ProtocolLib version 5.1.0-SNAPSHOT-654
[05:42:23] [Server thread/INFO]: Provides read/write access to the Minecraft protocol.
[05:42:23] [Server thread/INFO]: Authors: dmulloy2 and comphenix
[05:42:24] [Server thread/INFO]: This server is running Paper version git-Paper-84 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: c016e03)
You are running the latest version
[05:48:39] [Server thread/INFO]: Server Plugins (3):
[05:48:39] [Server thread/INFO]: Bukkit Plugins:
[05:48:39] [Server thread/INFO]:  - FastAsyncWorldEdit, Oraxen, ProtocolLib
```

```
all_sided_blast_furnace:
  displayname: <white>All Sided Blast Furnace
  material: PAPER
  Pack:
    generate_model: true
    custom_model_data: 1003004
    parent_model: block/cube_all
    textures:
    - block/blast_furnace_top.png
  Mechanics:
    noteblock:
      model: all_sided_blast_furnace
      custom_variation: 304
      hardness: 6
      drop:
        minimal_type: STONE
        best_tools:
        - PICKAXE
        silktouch: false
        loots:
        - oraxen_item: all_sided_blast_furnace
          probability: 1.0
```

settings.yml
```
  worldedit: # Please note these are both experimental still and should be used with caution
    noteblock_mechanic: true
    stringblock_mechanic: false # Works, but is buggy with some stringblocks, specifically with Tall-property
```

fawe config.yml
```
extent:
  # Don't bug console when these plugins slow down WorldEdit operations
  #  - You'll see a message in console or ingame if you need to change this option
  allowed-plugins: 
  - "com.example.ExamplePlugin"
  - "io.th0rgal.oraxen.compatibilities.provided.worldedit.WorldEditHandlers$1"
  # Should debug messages be sent when third party extents are used?
  debug: true
```

**Comment by Boy0000** [comment]
and are you building the 1.158.1 PR and testing or are you using master/spigot release?

**Comment by noiverre** [comment]
This issue is solved IF legacy block mechanics, stringblock mechanics, noteblock mechanics, and furniture mechanics is enabled in mechanics.yml

**Comment by Boy0000** [comment]
what did you disable in mechanics.yml for this to appear for noteblocks?

**Comment by noiverre** [comment]
Every custom block mechanics but noteblocks
